[package]
name = "iris"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10.1"
rand = "0.8.5"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
spake2 = "0.4.0"
thiserror = "1.0.61"
tracing = "0.1.40"
